# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class GreetingAndSumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GreetPerson = channel.unary_unary(
                '/GreetingAndSum/GreetPerson',
                request_serializer=service__pb2.GreetingRequest.SerializeToString,
                response_deserializer=service__pb2.GreetingResponse.FromString,
                )
        self.AddTwoNumbers = channel.unary_unary(
                '/GreetingAndSum/AddTwoNumbers',
                request_serializer=service__pb2.SumRequest.SerializeToString,
                response_deserializer=service__pb2.SumResponse.FromString,
                )


class GreetingAndSumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GreetPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTwoNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreetingAndSumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GreetPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.GreetPerson,
                    request_deserializer=service__pb2.GreetingRequest.FromString,
                    response_serializer=service__pb2.GreetingResponse.SerializeToString,
            ),
            'AddTwoNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTwoNumbers,
                    request_deserializer=service__pb2.SumRequest.FromString,
                    response_serializer=service__pb2.SumResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GreetingAndSum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreetingAndSum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GreetPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GreetingAndSum/GreetPerson',
            service__pb2.GreetingRequest.SerializeToString,
            service__pb2.GreetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTwoNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GreetingAndSum/AddTwoNumbers',
            service__pb2.SumRequest.SerializeToString,
            service__pb2.SumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
