# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\">\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x05style\x18\x02 \x01(\x0e\x32\x0e.GreetingStyle\",\n\x10GreetingResponse\x12\x18\n\x10greeting_message\x18\x01 \x01(\t\"9\n\nSumRequest\x12\x14\n\x0c\x66irst_number\x18\x01 \x01(\x05\x12\x15\n\rsecond_number\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03*)\n\rGreetingStyle\x12\n\n\x06\x46ORMAL\x10\x00\x12\x0c\n\x08INFORMAL\x10\x01\x32p\n\x0eGreetingAndSum\x12\x32\n\x0bGreetPerson\x12\x10.GreetingRequest\x1a\x11.GreetingResponse\x12*\n\rAddTwoNumbers\x12\x0b.SumRequest\x1a\x0c.SumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GREETINGSTYLE']._serialized_start=217
  _globals['_GREETINGSTYLE']._serialized_end=258
  _globals['_GREETINGREQUEST']._serialized_start=17
  _globals['_GREETINGREQUEST']._serialized_end=79
  _globals['_GREETINGRESPONSE']._serialized_start=81
  _globals['_GREETINGRESPONSE']._serialized_end=125
  _globals['_SUMREQUEST']._serialized_start=127
  _globals['_SUMREQUEST']._serialized_end=184
  _globals['_SUMRESPONSE']._serialized_start=186
  _globals['_SUMRESPONSE']._serialized_end=215
  _globals['_GREETINGANDSUM']._serialized_start=260
  _globals['_GREETINGANDSUM']._serialized_end=372
# @@protoc_insertion_point(module_scope)
